# Generated by Django 6.0.2 on 2026-02-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_comment_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
